
services:
  postgres:
    image: postgres:latest
    container_name: krisefiks_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    networks:
      - app-network

#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db
#      - SPRING_DATASOURCE_USERNAME=bruker
#      - SPRING_DATASOURCE_PASSWORD=passord
#    networks:
#      - app-network
#
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "5173:5173"
#    depends_on:
#      - backend
#    networks:
#      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
